language: python
python:
  - 3.7
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
   - pip install .  # install this package
   - pip install -r requirements.txt  # install the dependencies
script:
    - python3 -m pytest test_pkg.py   # run pytest
after_success:
  - codecov # submit coverage